# Generated by Django 5.0.1 on 2024-01-28 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('origin', models.IntegerField()),
            ],
            options={
                'db_table': 'food',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoodClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=255)),
                ('origin', models.IntegerField()),
            ],
            options={
                'db_table': 'food_class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoodAminoacid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triptofano', models.DecimalField(decimal_places=2, max_digits=4)),
                ('treonina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('isoleucina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('leucina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lisina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('metionina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cistina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fenilalanina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tirosina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('arginina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('histidina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alanina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acido_aspartico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acido_glutamico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('glicina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prolina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('serina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('food', models.ForeignKey(db_column='food', on_delete=django.db.models.deletion.DO_NOTHING, to='nutrition.food')),
            ],
            options={
                'db_table': 'food_aminoacid',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='food',
            name='food_class',
            field=models.ForeignKey(db_column='food_class', on_delete=django.db.models.deletion.DO_NOTHING, to='nutrition.foodclass'),
        ),
        migrations.CreateModel(
            name='FoodFatty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monoinsaturados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poliinsaturados', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('c12_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('c14_0', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c16_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('c18_0', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('c20_0', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c22_0', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c24_0', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c14_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c16_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c18_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('c20_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c18_2n6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('c18_3n3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('c20_4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c20_5', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c22_5', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c22_6', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c18_1t', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('c18_2t', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('food', models.ForeignKey(db_column='food', on_delete=django.db.models.deletion.DO_NOTHING, to='nutrition.food')),
            ],
            options={
                'db_table': 'food_fatty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoodNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umidade', models.IntegerField(blank=True, null=True)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('kj', models.IntegerField(blank=True, null=True)),
                ('proteina', models.FloatField(blank=True, null=True)),
                ('lipideos', models.FloatField(blank=True, null=True)),
                ('colesterol', models.FloatField(blank=True, null=True)),
                ('carboidrato', models.FloatField(blank=True, null=True)),
                ('fibra_alimentar', models.FloatField(blank=True, null=True)),
                ('cinzas', models.FloatField(blank=True, null=True)),
                ('calcio', models.FloatField(blank=True, null=True)),
                ('magnesio', models.FloatField(blank=True, null=True)),
                ('manganes', models.FloatField(blank=True, null=True)),
                ('fosforo', models.FloatField(blank=True, null=True)),
                ('ferro', models.FloatField(blank=True, null=True)),
                ('sodio', models.FloatField(blank=True, null=True)),
                ('potassio', models.FloatField(blank=True, null=True)),
                ('cobre', models.FloatField(blank=True, null=True)),
                ('zinco', models.FloatField(blank=True, null=True)),
                ('retinol', models.FloatField(blank=True, null=True)),
                ('re', models.FloatField(blank=True, null=True)),
                ('rae', models.FloatField(blank=True, null=True)),
                ('tiamina', models.FloatField(blank=True, null=True)),
                ('riboflavina', models.FloatField(blank=True, null=True)),
                ('piridoxina', models.FloatField(blank=True, null=True)),
                ('niacina', models.FloatField(blank=True, null=True)),
                ('vitamina_c', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('food', models.ForeignKey(db_column='food', on_delete=django.db.models.deletion.DO_NOTHING, to='nutrition.food')),
            ],
            options={
                'db_table': 'food_nutrients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoodMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('food', models.ForeignKey(db_column='food', on_delete=django.db.models.deletion.DO_NOTHING, to='nutrition.food')),
                ('meal', models.ForeignKey(db_column='meal', on_delete=django.db.models.deletion.DO_NOTHING, to='nutrition.meal')),
            ],
            options={
                'db_table': 'food_meal',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.DO_NOTHING, to='nutrition.plan'),
        ),
    ]
